### ISSUE TITLE
Joints prediction is outside the mesh

### ISSUE THREAD

**Issue by adrianofragomeni** [hassony2/manopth#10]
Hello,

I have a problem when I use this MANO implementation. After some epochs, some predicted joints are outside the mesh. How is it possible?
I attach a picture to give an idea about the problem.
![Capture](https://user-images.githubusercontent.com/31849297/73079978-5f812500-3ec5-11ea-8688-14b0d3152114.PNG)

**Comment by hassony2** [comment]
Hi @adrianofragomeni,

Thank you for your feedback !
You mention that you are training the method, what code are you using for training ?
Would it be possible that you are optimizing over buffer parameters of the mano model ?

Best,

Yana

**Comment by adrianofragomeni** [comment]
HI @hassony2,
I am using the manobranch.py you used in obman_train, where the parameters `self.lambda_shape` and 
`self.lambda_pose_reg` are not None.  For this reason am using two losses on these Mano parameters. Could it be this the problem?

Best,
Adriano

**Comment by hassony2** [comment]
Something that might produce such results would be you having switched the parameter mano_adapt_skeleton https://github.com/hassony2/obman_train/blob/83be15c342e24b332555b75b69544cb2eaa65cdb/mano_train/networks/handnet.py#L49 to True, which allows the method to also redefine hand joints during training.

**Comment by hassony2** [comment]
I don't think it would have to do with `self.lambda_shape` or `self.lambda_pose_reg`, but I am not 100% sure :)

**Comment by adrianofragomeni** [comment]
You were right, I had the `mano_adapt_skeleton ` parameter set to True. I will try to switch it to False and I let you know if it works.

Thank you

Adriano Fragomeni

**Comment by foamliu** [comment]
Thank you very much for the great work! 

Just in case it helps a little bit: do we need to adjust joint locations after the vertice are conditioned on pose?

![image](https://user-images.githubusercontent.com/14009435/83733823-ad324900-a680-11ea-990b-e7844d360cc4.png)

**Comment by dimtziwnas** [comment]
Dear @foamliu , thank you for your comment.  The implementation is right as it is.

Please have a look at the [SMPL paper](http://files.is.tue.mpg.de/black/papers/SMPL2015.pdf), the formulation of which we follow also for [MANO](https://ps.is.tuebingen.mpg.de/uploads_file/attachment/attachment/392/Embodied_Hands_SiggraphAsia2017.pdf).

Please see Eq.10 on page 5.  The joint regressor of the model is applied after applying the shape blend shapes on the average template, and _before_ posing the model.

This is a common misconception, because other people train different regressors that are applied after applying both the shape and pose blend shapes.  Any regressor should be applied in the exact way it is trained for; different regressors might be trained for different ways of use.
